apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-b7hx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-b7hx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0052-app
  name: devfile-sample-b7hx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-b7hx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-b7hx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-b7hx@sha256:1e1f686acfdbe13cbd7feb52f565d915d101c162f0f6f11a95ef603e64b66e1d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
