apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-b7hx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-b7hx@sha256:1e1f686acfdbe13cbd7feb52f565d915d101c162f0f6f11a95ef603e64b66e1d
        name: my-nodejs
        resources: {}
status: {}
